
# AUTOMATICALLY GENERATED BY THE PDL TOPLEVEL Makefile.PL.
# DO NOT HAND-EDIT - CHANGES WILL BE LOST UPON YOUR NEXT
#  'perl Makefile.PL'!!!
package PDL;
use File::Spec;
%PDL::Config = (
	BADVAL_PER_PDL	=>	"0",
	BADVAL_USENAN	=>	"0",
	F77CONF	=>	"\/build\/pdl\-ZicM0k\/pdl\-2\.020\/debian\/f77conf\.pl",
	FITS_LEGACY	=>	"1",
	GD_DEFINE	=>	"",
	GD_INC	=>	undef,
	GD_LIBS	=>	undef,
	GL_BUILD	=>	"1",
	GSL_INC	=>	undef,
	GSL_LIBS	=>	undef,
	HDF_INC	=>	["\/usr\/include\/hdf"],
	HDF_LIBS	=>	undef,
	HIDE_TRYLINK	=>	"1",
	HTML_DOCS	=>	"1",
	MALLOCDBG	=>	{
"include" => "",
"libs" => ""
		},
	MINUIT_LIB	=>	undef,
	OPTIMIZE	=>	undef,
	PDLDOC_IGNORE_AUTOLOADER	=>	"0",
	PDL_BUILD_DIR	=>	"\/build\/pdl\-ZicM0k\/pdl\-2\.020",
	PDL_BUILD_VERSION	=>	"2\.020",
	PDL_CONFIG_VERSION	=>	"0\.005",
	POGL_VERSION	=>	"0\.6702",
	POGL_WINDOW_TYPE	=>	"glut",
	POSIX_THREADS_INC	=>	undef,
	POSIX_THREADS_LIBS	=>	undef,
	PROJ_INC	=>	undef,
	PROJ_LIBS	=>	undef,
	SKIP_KNOWN_PROBLEMS	=>	"0",
	TEMPDIR	=>	"\/tmp",
	USE_POGL	=>	"1",
	WITH_3D	=>	"1",
	WITH_BADVAL	=>	"1",
	WITH_DEVEL_REPL	=>	"1",
	WITH_GD	=>	"1",
	WITH_GSL	=>	"1",
	WITH_HDF	=>	"1",
	WITH_IO_BROWSER	=>	"1",
	WITH_MINUIT	=>	"1",
	WITH_POSIX_THREADS	=>	"1",
	WITH_PROJ	=>	"0",
	WITH_SLATEC	=>	"1",
);
1;